/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/Index" |
  "/pages/chat/Detail" |
  "/pages/complaint/Appeal" |
  "/pages/complaint/Detail" |
  "/pages/complaint/Index" |
  "/pages/complaint/Record" |
  "/pages/fee/Index" |
  "/pages/goods/Apply" |
  "/pages/goods/Detail" |
  "/pages/goods/Mine" |
  "/pages/goods/Publish" |
  "/pages/login/Index" |
  "/pages/message/Index" |
  "/pages/mine/Index" |
  "/pages/order/Detail" |
  "/pages/order/List" |
  "/pages/order/Review" |
  "/pages/school/Index" |
  "/pages/security/Index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/Index" | "/pages/message/Index" | "/pages/mine/Index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
